# Generated by Django 4.1 on 2022-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_code',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
